# numpy exercise

In [1]:
import numpy as np

## 1. Literal array definition

In [2]:
A = np.array([
    [1, 3, 5, 7],
    [2, 4, 6, 8],
    [3, 5, 7, 9]
])

A

array([[1, 3, 5, 7],
       [2, 4, 6, 8],
       [3, 5, 7, 9]])

In [3]:
b = np.array([1, 2, 3, 4])
b

array([1, 2, 3, 4])

## 2. Array dimensions

numpy.ndarray.**shape**  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.shape.html

In [4]:
# 2-D array
A.shape

(3, 4)

In [5]:
# dimensions unpacking
n, m = A.shape

print('rows:', n)
print('cols:', m)

rows: 3
cols: 4


In [6]:
# 1-D array
b.shape

(4,)

In [7]:
c = b.reshape(1, -1)
c

array([[1, 2, 3, 4]])

In [8]:
# 2-D array
c.shape

(1, 4)

**Recommendation: avoid using 1-D arrays where possible** due to complex matrix operations rules: result may be surprising/unpredictable
  
use numpy.**reshape** to transform them into 2-D  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html

2.1. Create matrix $C$ by reshaping vector $c$ into dimensions $2 \times 2$

In [19]:
C = c.reshape(2, 2)
C

array([[1, 2],
       [3, 4]])

## 3. Matrix indexing and slicing

See docs:  
https://docs.scipy.org/doc/numpy-1.10.0/user/basics.indexing.html

or find some easier tutorial

3.1. Select $A_{1, 2}$

In [23]:
A[1, 2]

6

3.2. Select second column of $A$

In [24]:
A[:, 1]

array([3, 4, 5])

3.3. Select first two columns of $A$

In [25]:
A[:, :2]

array([[1, 3],
       [2, 4],
       [3, 5]])

3.4. Select last row of $A$

In [26]:
A[-1, :]

array([3, 5, 7, 9])

3.5. Select 1st and 3rd columns of $A$

In [27]:
A[:, [0, 2]]

array([[1, 5],
       [2, 6],
       [3, 7]])

## 4. Matrix operations
4.1. Transpose matrices $A, c$: get $A^T, c^T$  

numpy.ndarray.**transpose**  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.transpose.html

numpy.ndarray.**T** (shortcut)  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.T.html

In [33]:
A.T

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7],
       [7, 8, 9]])

In [34]:
c.T

array([[1],
       [2],
       [3],
       [4]])

4.2. Multiply $A \cdot c^T$ (don't forget to transpose $c$ to make dimensions match)

numpy.**dot**  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html

In [48]:
np.dot(A, c.T)

array([[50],
       [60],
       [70]])

4.3. Multiply $A * D$ elementwise

numpy.**multiply**  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.multiply.html

Find shortcut for matrix elementwise multiplication!

In [49]:
D = np.array([
    [1, 2, 1, 2],
    [1, 2, 1, 2],
    [1, 2, 1, 2]
])

In [50]:
A * D

array([[ 1,  6,  5, 14],
       [ 2,  8,  6, 16],
       [ 3, 10,  7, 18]])

4.4. Add and subtract matrices: $A + D, A - D$  

numpy.**add**  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.add.html

numpy.**subtract**  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.subtract.html

Find shortcuts!

In [51]:
A + D

array([[ 2,  5,  6,  9],
       [ 3,  6,  7, 10],
       [ 4,  7,  8, 11]])

In [52]:
A - D

array([[0, 1, 4, 5],
       [1, 2, 5, 6],
       [2, 3, 6, 7]])

4.5. Divide $A$ by $D$ elementwise  

numpy.**divide**  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.divide.html  

Find shortcut!

In [53]:
A / D

array([[1. , 1.5, 5. , 3.5],
       [2. , 2. , 6. , 4. ],
       [3. , 2.5, 7. , 4.5]])

## 5. Broadcasting

See docs:  
https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html

In [54]:
# 1 is repeated 3 x 4 times to make dimensions match
A + 1

array([[ 2,  4,  6,  8],
       [ 3,  5,  7,  9],
       [ 4,  6,  8, 10]])

In [55]:
A * 2

array([[ 2,  6, 10, 14],
       [ 4,  8, 12, 16],
       [ 6, 10, 14, 18]])

In [56]:
A ** 2

array([[ 1,  9, 25, 49],
       [ 4, 16, 36, 64],
       [ 9, 25, 49, 81]])

In [57]:
# c is stacked 3 times to make dimensions match
A + c

array([[ 2,  5,  8, 11],
       [ 3,  6,  9, 12],
       [ 4,  7, 10, 13]])

## 6. Automated matrix creation

6.1. Generate $Z \in \mathbb{R}^{2 \times 4}$ matrix filled with zeros

numpy.**zeros**  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html

In [67]:
Z = np.zeros((2, 4))
Z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

6.2. Generate $U \in \mathbb{R}^{5 \times 4}$ matrix filled with uniformely distributed values in range $(-8, 12)$

numpy.random.**uniform**  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.uniform.html

In [68]:
U = np.random.uniform(-8, 13, size=(5, 4))
U

array([[-6.79254385, -6.68576073,  0.31945789, -7.45237902],
       [-0.07990758, -6.96863508,  6.62798234, -7.17826504],
       [ 9.55956998, -4.54083004, -3.61117944, 11.1476497 ],
       [10.38037961, -6.13971251, 11.60161965,  8.79060733],
       [-6.74425771,  4.05653169, 11.48547739, 11.2422876 ]])

6.3. Generate $N \in \mathbb{R}^{8 \times 3}$ matrix filled with normally distributed values with $\mu = 0$ and $\sigma = 5$

numpy.random.**normal**  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.normal.html

In [92]:
N = np.random.normal(0, 5, size=(8, 3))
N

array([[  1.72659986,   8.18078317,  -0.43830612],
       [  7.91725794,  -3.78647179,   0.44736032],
       [ -0.48784547,  -2.59754868,  -5.79500004],
       [  1.47177354,  -5.91871661,  -3.0217671 ],
       [-17.04939932,  -4.04144201,   6.80947685],
       [  9.7517029 ,   5.93304892,   9.30844626],
       [ -8.90468869,  -3.02935114,   1.71351688],
       [ -1.59393521,   0.70669603,  -2.22730693]])

## 7. Matrix aggregate functions

7.1. Find mean, min and max values in $U$

numpy.**mean**  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html

numpy.ndarray.**min**  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.min.html

numpy.ndarray.**max**  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.max.html

In [72]:
np.mean(U)

1.450904609297512

In [83]:
np.min(U)

-7.4523790157071925

In [84]:
np.max(U)

11.601619645886025

7.2. Find mean and standard deviation for each column of $N$

numpy.**std**  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.std.html

In [100]:
N.mean(0)

array([-0.89606681, -0.56912526,  0.84955251])

In [101]:
N.std(0)

array([8.13369982, 4.76524566, 4.72023056])

7.3. Find sum of all elements of $U$, also all row-wise and column-wise sums

numpy.**sum**  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.sum.html

In [97]:
U.sum()

29.018092185950238

In [98]:
U.sum(1)

array([-20.6112257 ,  -7.59882536,  12.5552102 ,  24.63289407,
        20.04003898])

In [99]:
U.sum(0)

array([  6.32324045, -20.27840667,  26.42335783,  16.54990058])

## 8. Other helpful functions

8.1. Create matrix $S$:
$S_{i, j}=
\begin{cases}
    1, & \text{if $N_{i, j} \ge 0$},\\
    -1, & \text{if $N_{i, j} < 0$}.
\end{cases}
$

numpy.**where**  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.where.html

In [116]:
S = np.where(N >= 0, 1, -1)
S

array([[ 1,  1, -1],
       [ 1, -1,  1],
       [-1, -1, -1],
       [ 1, -1, -1],
       [-1, -1,  1],
       [ 1,  1,  1],
       [-1, -1,  1],
       [-1,  1, -1]])